### ISSUE TITLE
FullAjaxExceptionHandler fails to handle an exception between rendering updates

### ISSUE THREAD

**Issue by VsevolodGolovanov** [omnifaces/omnifaces#111]
When using `FullAjaxExceptionHandler`, some exceptions during Render Response phase result in a malformed XML response, which doesn't contain `changes` opening tag - only closing one.

To reproduce it's necessary to trigger an exception while update is not started yet, e.g. during component tree rendering visiting. In my case this happened with an iterative component.

View:

```
<h:form>
    <h:dataTable id="zzz" value="#{bean.data}" />
    <p:commandButton value="Update" update="zzz"  />
</h:form>
```

Bean:

```
public List<String> getData() {
    if (FacesContext.getCurrentInstance().isPostback()
            && FacesContext.getCurrentInstance().getCurrentPhaseId() == PhaseId.RENDER_RESPONSE) {
        throw new RuntimeException();
    }
    return null;
}
```

The problem is that `OmniPartialResponseWriter` only decides to call `wrapped.endDocument();` if it was in the state of `updating` at the time. It could implement the `inChanges` tracking like `javax.faces.context.PartialResponseWriter` does it, or just call `wrapped.endDocument();` on `reset` unconditionally.

**Comment by BalusC** [comment]
Which JSF impl/version?

Can't reproduce with Mojarra 2.2.10 / MyFaces 2.2.6.

By the way, business logic in getters == wrong.

**Comment by VsevolodGolovanov** [comment]
I've made a reproducer: https://drive.google.com/file/d/0B7odbfohhRNTVnpQMm1SUnZNalk/view?usp=sharing
The issue does persist in Mojarra 2.2.10.
During reproducing I've also discovered, that if an exception is thrown during tree visiting before any updates were rendered, then error page rendering results in another kind of malformed XML.

(In the real application it's actually lazy initialization, not so much business logic.)

**Comment by VsevolodGolovanov** [comment]
Sorry, I made the reproducer in such a way that it doesn't start with OF2.0 due to CDI detection. The issue is reproducible with OF1.10.
Also with Mojarra 2.2.10 the "Throw exception during updating on Render Response" test fails for some reason. The same test passes correctly in 2.2.8-2.2.9. The exception suggests that it's a Mojarra issue.

**Comment by BalusC** [comment]
Reproduced on WildFly 8.2 + Mojarra 2.2.8. Doesn't seem to be a trivial fix at first sight. There are no conditions I could hook on.

**Comment by BalusC** [comment]
While working on #248 I discovered an opportunity to solve this problem. It was quite simple: just flush the JSF response writer. On the contrary to the expectation, it does not flush the underlying writer, but clears its internal state and buffer. This is even explicitly mentioned in API doc http://docs.oracle.com/javaee/7/api/javax/faces/context/ResponseWriter.html#flush--

Fix is available in today's [2.4-SNAPSHOT](https://oss.sonatype.org/content/repositories/snapshots/org/omnifaces/omnifaces/2.4-SNAPSHOT).

**Comment by VsevolodGolovanov** [comment]
This is still reproducible with Mojarra 2.3.3.SP1 and OminFaces 3.11.2.
Flush call does nothing, because closeStart=false:
![image](https://user-images.githubusercontent.com/8070317/139714824-b64ff115-ff55-434e-b6d2-4a04c069d4bf.png)
I didn't debug further than that.

We did a nasty Mojarra specific workaround back then, so we'll keep using it:
```
public class RenderExceptionResponseResetFilter implements Filter {

	private static final Logger log = Logger.getLogger(RenderExceptionResponseResetFilter.class);

	@Override
	public void doFilter(ServletRequest request, ServletResponse response, FilterChain chain)
			throws IOException, ServletException {
		HttpServletRequest httpRequest = (HttpServletRequest) request;
		if (!FacesRequestUtils.isResourseRequest(httpRequest)) {
			response = new RenderExceptionResponseResetWrapper((HttpServletResponse) response);
		}
		chain.doFilter(request, response);
	}

	@Override
	public void init(FilterConfig fConfig) throws ServletException {
	}

	@Override
	public void destroy() {
	}

	private static class RenderExceptionResponseResetWrapper extends HttpServletResponseWrapper {

		public RenderExceptionResponseResetWrapper(HttpServletResponse wrappedResponse) {
			super(wrappedResponse);
		}

		@Override
		public void reset() {
			PartialViewContext context = Faces.getContext().getPartialViewContext();
			if (context.isAjaxRequest() && context.isPartialRequest()) {
				PartialResponseWriter writer = context.getPartialResponseWriter();
				if (isBetweenUpdatesState(writer)) {
					log.debug("Reset response while rendering between updates");
					try {
						writer.startError("");
						writer.endError();
						writer.endElement("partial-response"); // Don't use endDocument() as it will flush.
					} catch (IOException e) {
						log.error("Failed to end partial response", e);
					}
				}
			}
			super.reset();
		}

		private boolean isBetweenUpdatesState(PartialResponseWriter writer) {
			do {
				if (ReflectionUtils.<Boolean> getFieldValue(writer.getClass(), "inChanges", writer)) {
					return !ReflectionUtils.<Boolean> getFieldValue(writer.getClass(), "inUpdate", writer);
				}
				try {
					writer = (PartialResponseWriter) writer.getWrapped();
				} catch (ClassCastException e) {
					return false;
				}
			} while (writer != null);
			return false;
		}
	}
}
```

**Comment by BalusC** [comment]
I tried your reproducer from 11 March 2015 once more. There are 4 buttons. Before OmniFaces 2.4, only the first one worked. After OmniFaces 2.4, the first three ones worked and only the last one failed. This one must have slipped through during fixing. I can see how your work around solves that.

**Comment by BalusC** [comment]
Fixed now. Thank you for getting back to this!
